/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author fernando
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jm_iniciar_sesion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        ferk = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_iniciar_sesion = new javax.swing.JMenuItem();
        jm_menu = new javax.swing.JMenu();
        jmi_clientes = new javax.swing.JMenuItem();
        jmi_usuarios = new javax.swing.JMenuItem();
        jmi_empleados = new javax.swing.JMenuItem();
        jm_sistema = new javax.swing.JMenu();
        jmi_reservaciones = new javax.swing.JMenuItem();
        jmi_servicios = new javax.swing.JMenuItem();
        jmi_inventario = new javax.swing.JMenuItem();
        jm_efectivo = new javax.swing.JMenu();
        jmi_ingresos = new javax.swing.JMenuItem();
        jmi_egreso = new javax.swing.JMenu();
        jmi_agregar_egreso = new javax.swing.JMenuItem();
        jmi_consultar_egreso = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenu();
        jmi_cerrar_sesion = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jm_iniciar_sesion.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ferk.setText("@ferk");

        jm_archivo.setText("Archivo");

        jmi_iniciar_sesion.setText("Iniciar Sesión");
        jm_archivo.add(jmi_iniciar_sesion);

        jMenuBar1.add(jm_archivo);

        jm_menu.setText("Menú");
        jm_menu.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        jmi_clientes.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_clientes.setText("Clientes");
        jm_menu.add(jmi_clientes);

        jmi_usuarios.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_usuarios.setText("Usuarios");
        jm_menu.add(jmi_usuarios);

        jmi_empleados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmi_empleados.setText("Empleados");
        jm_menu.add(jmi_empleados);

        jMenuBar1.add(jm_menu);

        jm_sistema.setText("Sistema");
        jm_sistema.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        jmi_reservaciones.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_reservaciones.setText("Reservaciones");
        jm_sistema.add(jmi_reservaciones);

        jmi_servicios.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_servicios.setText("Servicios");
        jm_sistema.add(jmi_servicios);

        jmi_inventario.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_inventario.setText("Inventario");
        jm_sistema.add(jmi_inventario);

        jMenuBar1.add(jm_sistema);

        jm_efectivo.setText("Efectivo");
        jm_efectivo.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        jmi_ingresos.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_ingresos.setText("Ingresos");
        jm_efectivo.add(jmi_ingresos);

        jmi_egreso.setText("Egresos");

        jmi_agregar_egreso.setText("Agregar Egreso");
        jmi_egreso.add(jmi_agregar_egreso);

        jmi_consultar_egreso.setText("Consultar Egresos");
        jmi_egreso.add(jmi_consultar_egreso);

        jm_efectivo.add(jmi_egreso);

        jMenuBar1.add(jm_efectivo);

        jm_salir.setText("Salir");
        jm_salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jmi_cerrar_sesion.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jmi_cerrar_sesion.setText("Cerrar Sesión");
        jm_salir.add(jmi_cerrar_sesion);

        jMenuBar1.add(jm_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1233, Short.MAX_VALUE)
                .addComponent(ferk)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(640, Short.MAX_VALUE)
                .addComponent(ferk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ferk;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu6;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenu jm_archivo;
    public javax.swing.JMenu jm_efectivo;
    public javax.swing.JMenu jm_iniciar_sesion;
    public javax.swing.JMenu jm_menu;
    public javax.swing.JMenu jm_salir;
    public javax.swing.JMenu jm_sistema;
    public javax.swing.JMenuItem jmi_agregar_egreso;
    public javax.swing.JMenuItem jmi_cerrar_sesion;
    public javax.swing.JMenuItem jmi_clientes;
    public javax.swing.JMenuItem jmi_consultar_egreso;
    public javax.swing.JMenu jmi_egreso;
    public javax.swing.JMenuItem jmi_empleados;
    public javax.swing.JMenuItem jmi_ingresos;
    public javax.swing.JMenuItem jmi_iniciar_sesion;
    public javax.swing.JMenuItem jmi_inventario;
    public javax.swing.JMenuItem jmi_reservaciones;
    public javax.swing.JMenuItem jmi_servicios;
    public javax.swing.JMenuItem jmi_usuarios;
    // End of variables declaration//GEN-END:variables
}
